### PR TITLE
Caltrack formatter bug fixes

### PR DESCRIPTION
**Pull request by tplagge**
This should fix two of the commonly-occurring errors in the Caltrack model run.

### CODE REVIEW

**Comment by marcpareoee** [comment]
Add a unit test that fails without this addition?

**Comment by mcgeeyoung** [comment]
@tplagge Will rerunning the CalTrack meters change after we merge this fix in?

**Comment by tplagge** [comment]
@mcgeeyoung Yes, more traces should be included in the results, particularly those with short duration traces.

@marcpareoee Good idea, will add this.

**Comment by tplagge** [comment]
In fact, please hold off on merging until I've done one more commit. That test turned out to be useful.

**Comment by tplagge** [comment]
OK, ready.

**Comment by philngo** [comment]
@tplagge Now that I've merged this, we should move these changes (as applicable) into the caltrack model where this logic is now housed. This will be more involved than just a merge/rebase. I've taken a stab at it over in feature/time-based-derivatives.

**Comment by tplagge** [comment]
Cool, I just committed it [here](https://github.com/openeemeter/eemeter/commit/fdb0958f4b817962dd9e2509f9ff698f4ca0b8f4)

**Pull request merged**
