### PR TITLE
Feature/international

### PR DESCRIPTION
**Pull request by jfenna**
### Your checklist for this pull request

Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a feature/bugfix branch** (right side). Don't request your master!
- [X] Make sure tests pass and coverage has not fallen `docker-compose run --rm test`.
- [X] Update the [CHANGELOG.md](../CHANGELOG.md) to describe your changes in a bulleted list under the "Development" section at the top of the changelog. If this section does not exist, create it.
- [X] Make sure code style follows PEP 008 using `docker-compose run --rm blacken`.
- [X] Make sure that new functions and classes have inline docstrings and are
  included in [docs/api.rst](../docs/api.rst) for the sphinx build. Please use [numpy-style docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#google-vs-numpy).
  Sphinx docs can be built with the following command: `docker-compose run --rm --entrypoint="make -C docs html" shell`. Please note and fix any warnings.
- [x] Make sure that all git commits are have the "Signed-off-by" message for
  the Developer Certificate of Origin. When you're making a commit, just add
  the `-s/--signoff` flag (e.g., `git commit -s`).

### Description

EEMeter International is an international extension to enable EEMeter to operate with ease outside of the United States. Amendments include:

- Inclusion of a new `processing.py ` module to allow for easy preprocessing of data for eemeter format. `setup.py` and `__init__.py` amended accordingly.
- Inclusion of a new set of sample datasets corresponding to UK energy consumption and temperature data.
- Inclusion of a regional toggle to EEMeter, manifest principally in amendments to 'design_matrices.py`, `derivatives.py` and `features.py`.
- Inclusion of a new `region_info.csv` file corresponding to standard heating/cooling balance points for USA, UK, France, Germany and Spain.
- Updating of licencing scripts to 2023.
- Addition of new tests.
- Amendments to `tutorial.ipynb`.
- Addition of new `eemeter international.ipynb` tutorial notebook.

Detailed descriptions, plus tutorials, demonstrations and testing of amendments can be found in the amendments to `tutorial.ipynb` and `eemeter international.ipynb`.

### CODE REVIEW

**Comment by jfenna** [comment]
Hi Phil,

Thanks so much for providing this feedback. A few comments below:

- Happy to remove `sum_gas_and_elec()` = this has been removed in the latest push. 
- I have moved 'eemeter_hourly()' and 'eemeter_daily()' to a new module `quickstart.py`, replacing 'eemeter' for 'caltrack' as requested: `hourly.py` and `usage_per_day.py` could not accommodate these functions due to issues of circularity.
- All other wrangling functions moved to `transform.py`.

On the unit tests - I'm not getting this my end, all the tests pass even after recloning into a separate local dir. Really not sure what this could be - would you mind trying again/elaborating on this item?

On the regional temperature handling - could you elaborate on what the issue is with expanding the hardcoded balance points by way of `region_info.csv`? Is it a space issue? If so, I can send through an update to the documentation with a list of recommended balance points and a methodology for updating them, though this would come at the cost of accessibility - the benefit to linking region to recommended balance points is that in the current PR eemeter hourly automatically assigns balance points AND units depending on your location.

Let me know what you think - J.

**Comment by jason-recurve** [comment]
Hey James,

I believe the unit test failures were due to a stale docker image on my end. After rebuilding with the updates, everything passes.

Regarding the temperature units and balance points:
* Decoupling the units from region feels more flexible, as a global data source will probably use Celsius even for USA
* Hardcoding static balance points makes me uneasy, as these will change over time with the climate. It might not be obvious that eemeter needs to be patched to reflect updated temperature assumptions if they are included as defaults per-location

There's one other reason we'd rather leave out the regions concept for now: we'd still like to bring this more officially before the working group, as it would be a more fundamental change to the model than simply using different units. Perhaps the working group will also evaluate different model formulations which make the model less dependent on these sorts of magic numbers. It seems best to us in the meantime to channel effort toward making it easier to override the defaults--this seems appropriate and doesn't need approval, since the scope of OpenEEmeter includes model testing as well as reference implementations.

**Comment by jfenna** [comment]
Hi Jason,

Apologies for the slightly delay in getting back to you here. I've amended the code so that these elements reflect EEMeter 'as is', with temperature conversions included as an optional degC toggle, defaulting to False. Tests all run fine. 

Let me know what you think. If you're in principle happy I can go ahead and update the eemeter_international notebook; alternatively if you think this is better integrated to the general tutorial notebook just say.

**Comment by jfenna** [comment]
Hi Jason,

Apologies for the slightly delay in getting back to you here. I've amended the code so that these elements reflect EEMeter 'as is', with temperature conversions included as an optional degC toggle, defaulting to False. Tests all run fine.

Let me know what you think. If you're in principle happy I can go ahead and update the eemeter_international notebook; alternatively if you think this is better integrated to the general tutorial notebook just say.

**Comment by jfenna** [comment]
@jason-recurve - apologies for the extended delay. I've updated the Jupyter notebook with the relevant information; I have also updated the repo to account for recent changes. Hopefully this wraps everything up, please let me know if there is anything else.

**Review by jason-recurve — APPROVED** [review]

**Pull request merged**
